
defaults:
  - _self_

# misc
use_tb: true
seed: 1
device: cuda
GUI: false
save_snapshot: true

# training specs
total_number_of_training_steps: 100000
evaluate_every: 5000
learning_rate: 1e-4
augment: false

#env
accuracy_error_weight: 2
side_pick_only: true
add_noise: false
image_height: 64
image_width: 64
reward_id: 0

#expert data
path2data: store_expert_data/2023.03.13/expert_data.pkl

#policy to evaluate
evaluate_only: false
eval_only_iterations: 3
path2policy: ???

hydra:
  run:
    dir: ./train_from_demonstr/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}

