
agent_name: REDQ

agent:
  _target_: agents.REDQ.REDQ_Agent
  input_shape: ??? # to be specified later
  workspace: ???
  device: ${device}
  use_tb: ${use_tb}
  critic_target_tau: ${critic_target_tau}
  decoder_nc: 1
  learning_rate: ${learning_rate}
  num_Q: ${num_Q}
  num_min: ${num_min}
  num_update: ${num_update}
  exploration_rate: 0.1
  num_expl_steps: ${num_expl_steps}
  from_segm: ${from_segm}
  safety_mask: ${safety_mask}

