
defaults:
  - _self_

# misc
use_tb: true
seed: 1
device: cuda
GUI: true
save_snapshot: true

# training specs
total_number_of_training_steps: 100000
evaluate_every: 5000
learning_rate: 1e-4
augment: true

#env
accuracy_error_weight: 2
side_pick_only: true
add_noise: true
image_height: 160
image_width: 160

#expert data
path2data: store_expert_data/2022.08.10/185853_GUI=false,num_episodes=1,side_pick_only=true/expert_data.pkl

#policy to evaluate
evaluate_only: false
eval_only_iterations: 10
path2policy: ???

hydra:
  run:
    dir: ./train_from_demonstr/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}

