
defaults:
  - _self_

#misc
num_episodes: 10
GUI: true
seed: 1

#data
resize_height: 160
resize_width: 160

#env
side_pick_only: true
add_noise: false

hydra:
  run:
    dir: ./store_expert_data/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}

